-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_SG552",
WeaponType = "Rifle",
WorldModel = "models/weapons/w_rif_sg552.mdl",
ViewModel = "models/weapons/v_rif_sg552.mdl",
ViewModelFlip = true,
HoldType = "ar2",
Slot = 2,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = true,
MuzzleFlashScale = 1.3,
Sounds = {
    special3 = "Default.Zoom",
    single_shot = "Weapon_SG552.Single",
},
Primary = {
    Ammo = "BULLET_PLAYER_556MM",
    Automatic = true,
    Damage = 33,
    Penetration = 2,
    ClipSize = 30,
    CycleTime = 0.09,
    Accuracy = {
        InaccuracyJumpAlt = 0.3346,
        RecoveryTimeCrouch = 0.2763,
        InaccuracyCrouchAlt = 0.0028,
        InaccuracyStand = 0.0054,
        InaccuracyJump = 0.3346,
        MaxInaccuracy = 1,
        InaccuracyLandAlt = 0.0669,
        InaccuracyFire = 0.0122,
        InaccuracyLadderAlt = 0.0836,
        InaccuracyMoveAlt = 0.0613,
        InaccuracyLand = 0.0669,
        AccuracyOffset = 0.3,
        AccuracyDivisor = 220,
        SpreadAlt = 0.0006,
        InaccuracyMove = 0.0613,
        InaccuracyLadder = 0.0836,
        Spread = 0.0006,
        InaccuracyStandAlt = 0.0037,
        RecoveryTimeStand = 0.3868,
        InaccuracyFireAlt = 0.0085,
        InaccuracyCrouch = 0.004,
    },
    Bullets = 1,
    DefaultClip = 30,
    Range = 8192,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
WepSelData = {
    "CSweaponsSmall",
    "[",
},
IconOverride = "VGUI/gfx/VGUI/weapon_sg552",
IdleInterval = 20,
MuzzleFlashStyle = "CS_MUZZLEFLASH_X",
TimeToIdle = 2,
})