-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_USP45",
WeaponType = "Pistol",
WorldModel = "models/weapons/w_pist_usp.mdl",
ViewModel = "models/weapons/v_pist_usp.mdl",
ViewModelFlip = true,
HoldType = "pistol",
Slot = 1,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = false,
MuzzleFlashScale = 1,
Sounds = {
    special1 = "Weapon_USP.SilencedShot",
    single_shot = "Weapon_USP.Single",
    special2 = "Weapon_USP.DetachSilencer",
    special3 = "Weapon_USP.AttachSilencer",
},
Primary = {
    Ammo = "BULLET_PLAYER_45ACP",
    Automatic = false,
    Bullets = 1,
    CycleTime = 0.15,
    ClipSize = 12,
    Penetration = 1,
    Accuracy = {
        InaccuracyJumpAlt = 0.2962,
        RecoveryTimeCrouch = 0.2337,
        InaccuracyCrouchAlt = 0.006,
        InaccuracyStand = 0.008,
        InaccuracyJump = 0.2872,
        InaccuracyLandAlt = 0.0592,
        InaccuracyFire = 0.0349,
        InaccuracyLand = 0.0574,
        InaccuracyMove = 0.0172,
        InaccuracyMoveAlt = 0.0177,
        SpreadAlt = 0.003,
        InaccuracyLadderAlt = 0.0197,
        InaccuracyLadder = 0.0191,
        Spread = 0.004,
        InaccuracyStandAlt = 0.008,
        RecoveryTimeStand = 0.2804,
        InaccuracyFireAlt = 0.025,
        InaccuracyCrouch = 0.006,
    },
    Damage = 34,
    DefaultClip = 12,
    Range = 4096,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
CrosshairInfo = {
    x = 0,
    file = "sprites/crosshairs",
    y = 48,
    height = 24,
    width = 24,
},
WepSelData = {
    "CSweaponsSmall",
    "A",
},
IconOverride = "VGUI/gfx/VGUI/weapon_usp",
SilencerModel = "models/weapons/w_pist_usp_silencer.mdl",
})