-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_MAC10",
WeaponType = "SubMachinegun",
WorldModel = "models/weapons/w_smg_mac10.mdl",
ViewModel = "models/weapons/v_smg_mac10.mdl",
ViewModelFlip = true,
HoldType = "smg",
Slot = 2,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = false,
MuzzleFlashScale = 1.1,
Sounds = {
    single_shot = "Weapon_MAC10.Single",
},
Primary = {
    Ammo = "BULLET_PLAYER_45ACP",
    Automatic = true,
    Damage = 29,
    Penetration = 1,
    ClipSize = 30,
    CycleTime = 0.075,
    Accuracy = {
        AccuracyDivisor = 200,
        RecoveryTimeCrouch = 0.2526,
        InaccuracyFire = 0.0084,
        InaccuracyStand = 0.019,
        InaccuracyJump = 0.137,
        MaxInaccuracy = 1.65,
        InaccuracyLand = 0.0274,
        InaccuracyLadder = 0.0342,
        Spread = 0.001,
        InaccuracyMove = 0.0062,
        RecoveryTimeStand = 0.3536,
        AccuracyOffset = 0.6,
        InaccuracyCrouch = 0.0142,
    },
    Bullets = 1,
    DefaultClip = 30,
    Range = 4096,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
CrosshairInfo = {
    x = 0,
    file = "sprites/crosshairs",
    y = 48,
    height = 24,
    width = 24,
},
WepSelData = {
    "CSweaponsSmall",
    "L",
},
IconOverride = "VGUI/gfx/VGUI/weapon_mac10",
TimeToIdle = 2,
IdleInterval = 20,
})