-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_Scout",
WeaponType = "SniperRifle",
WorldModel = "models/weapons/w_snip_scout.mdl",
ViewModel = "models/weapons/v_snip_scout.mdl",
ViewModelFlip = true,
HoldType = "ar2",
Slot = 3,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = false,
MuzzleFlashScale = 1.1,
Sounds = {
    special3 = "Default.Zoom",
    single_shot = "Weapon_Scout.Single",
},
Primary = {
    Ammo = "BULLET_PLAYER_762MM",
    Automatic = false,
    Damage = 75,
    Penetration = 3,
    ClipSize = 10,
    CycleTime = 1.25,
    Accuracy = {
        InaccuracyJumpAlt = 0.3819,
        RecoveryTimeCrouch = 0.1768,
        InaccuracyCrouchAlt = 0.003,
        InaccuracyStand = 0.0317,
        InaccuracyJump = 0.3819,
        InaccuracyLandAlt = 0.0381,
        InaccuracyFire = 0.0666,
        AccuracyDivisor = -1,
        InaccuracyMoveAlt = 0.1909,
        InaccuracyLand = 0.0381,
        AccuracyOffset = 0,
        InaccuracyMove = 0.1909,
        SpreadAlt = 0.0003,
        InaccuracyLadderAlt = 0.0954,
        InaccuracyLadder = 0.0954,
        Spread = 0.0003,
        InaccuracyStandAlt = 0.004,
        RecoveryTimeStand = 0.2475,
        InaccuracyFireAlt = 0.0666,
        InaccuracyCrouch = 0.0237,
    },
    Bullets = 1,
    DefaultClip = 10,
    Range = 8192,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
WepSelData = {
    "CSweaponsSmall",
    "N",
},
IconOverride = "VGUI/gfx/VGUI/weapon_scout",
TimeToIdle = 1.8,
IdleInterval = 60,
CanScope = true,
MaxInaccuracy = 0,
})