-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_MP5",
WeaponType = "SubMachinegun",
WorldModel = "models/weapons/w_smg_mp5.mdl",
ViewModel = "models/weapons/v_smg_mp5.mdl",
ViewModelFlip = true,
HoldType = "smg",
Slot = 2,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = false,
MuzzleFlashScale = 1.1,
Sounds = {
    single_shot = "Weapon_MP5Navy.Single",
},
Primary = {
    Ammo = "BULLET_PLAYER_9MM",
    Automatic = true,
    Damage = 26,
    Penetration = 1,
    ClipSize = 30,
    CycleTime = 0.08,
    Accuracy = {
        AccuracyDivisor = 220,
        RecoveryTimeCrouch = 0.2796,
        InaccuracyFire = 0.0063,
        InaccuracyStand = 0.0171,
        InaccuracyJump = 0.2302,
        InaccuracyLand = 0.046,
        InaccuracyLadder = 0.0575,
        Spread = 0.001,
        InaccuracyMove = 0.0178,
        RecoveryTimeStand = 0.3914,
        AccuracyOffset = 0.45,
        InaccuracyCrouch = 0.0128,
    },
    Bullets = 1,
    DefaultClip = 30,
    Range = 4096,
},
Secondary = {
    Ammo = "BULLET_PLAYER_9MM",
    ClipSize = -1,
},
CrosshairInfo = {
    x = 0,
    file = "sprites/crosshairs",
    y = 48,
    height = 24,
    width = 24,
},
WepSelData = {
    "CSweaponsSmall",
    "X",
},
IconOverride = "VGUI/gfx/VGUI/weapon_mp5navy",
IdleInterval = 20,
TimeToIdle = 2,
MaxInaccuracy = 0.75,
})