-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_AWP",
WeaponType = "SniperRifle",
WorldModel = "models/weapons/w_snip_awp.mdl",
ViewModel = "models/weapons/v_snip_awp.mdl",
ViewModelFlip = true,
HoldType = "ar2",
Slot = 3,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = false,
MuzzleFlashScale = 1.35,
Sounds = {
    special3 = "Default.Zoom",
    single_shot = "Weapon_AWP.Single",
},
Primary = {
    Ammo = "BULLET_PLAYER_338MAG",
    Automatic = false,
    Damage = 115,
    Penetration = 3,
    ClipSize = 10,
    CycleTime = 1.5,
    Accuracy = {
        InaccuracyJumpAlt = 0.546,
        RecoveryTimeCrouch = 0.2467,
        InaccuracyCrouchAlt = 0.0015,
        InaccuracyLadderAlt = 0.1365,
        InaccuracyJump = 0.546,
        MaxInaccuracy = 0,
        InaccuracyLandAlt = 0.0546,
        InaccuracyFire = 0.14,
        AccuracyDivisor = -1,
        InaccuracyMoveAlt = 0.273,
        InaccuracyLand = 0.0546,
        AccuracyOffset = 0,
        InaccuracyMove = 0.273,
        SpreadAlt = 0.0002,
        InaccuracyStand = 0.0807,
        InaccuracyLadder = 0.1365,
        Spread = 0.0002,
        InaccuracyStandAlt = 0.002,
        RecoveryTimeStand = 0.3453,
        InaccuracyFireAlt = 0.14,
        InaccuracyCrouch = 0.0606,
    },
    Bullets = 1,
    DefaultClip = 10,
    Range = 8192,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
WepSelData = {
    "CSweaponsSmall",
    "R",
},
IconOverride = "VGUI/gfx/VGUI/weapon_awp",
CanScope = true,
IdleInterval = 60,
TimeToIdle = 2,
})