-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_AK47",
WeaponType = "Rifle",
WorldModel = "models/weapons/w_rif_ak47.mdl",
ViewModel = "models/weapons/v_rif_ak47.mdl",
ViewModelFlip = true,
HoldType = "ar2",
Slot = 2,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = true,
MuzzleFlashScale = 1.6,
Sounds = {
    single_shot = "Weapon_AK47.Single",
},
Primary = {
    Ammo = "BULLET_PLAYER_762MM",
    Automatic = true,
    Damage = 36,
    Penetration = 2,
    ClipSize = 30,
    CycleTime = 0.1,
    Accuracy = {
        AccuracyDivisor = 200,
        RecoveryTimeCrouch = 0.3486,
        InaccuracyFire = 0.0115,
        InaccuracyLand = 0.086,
        AccuracyOffset = 0.35,
        InaccuracyStand = 0.0091,
        InaccuracyLadder = 0.1076,
        Spread = 0.0006,
        InaccuracyMove = 0.0922,
        RecoveryTimeStand = 0.4881,
        InaccuracyJump = 0.4304,
        InaccuracyCrouch = 0.0068,
    },
    Bullets = 1,
    DefaultClip = 30,
    Range = 8192,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
CrosshairInfo = {
    x = 0,
    file = "sprites/crosshairs",
    y = 48,
    height = 24,
    width = 24,
},
WepSelData = {
    "CSweaponsSmall",
    "B",
},
IconOverride = "VGUI/gfx/VGUI/weapon_ak47",
MaxInaccuracy = 1.25,
IdleInterval = 20,
MuzzleFlashStyle = "CS_MUZZLEFLASH_X",
TimeToIdle = 1.9,
})