-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_Famas",
WeaponType = "Rifle",
WorldModel = "models/weapons/w_rif_famas.mdl",
ViewModel = "models/weapons/v_rif_famas.mdl",
ViewModelFlip = false,
HoldType = "ar2",
Slot = 2,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = true,
MuzzleFlashScale = 1.3,
Sounds = {
    single_shot = "Weapon_FAMAS.Single",
},
Primary = {
    Ammo = "BULLET_PLAYER_556MM",
    Automatic = true,
    Damage = 30,
    Penetration = 2,
    ClipSize = 25,
    CycleTime = 0.09,
    Accuracy = {
        InaccuracyJumpAlt = 0.3652,
        RecoveryTimeCrouch = 0.3032,
        InaccuracyCrouchAlt = 0.0041,
        InaccuracyStand = 0.0054,
        InaccuracyJump = 0.3652,
        InaccuracyLandAlt = 0.073,
        InaccuracyFire = 0.0118,
        InaccuracyLadderAlt = 0.0913,
        InaccuracyMoveAlt = 0.0697,
        InaccuracyLand = 0.073,
        AccuracyOffset = 0.3,
        AccuracyDivisor = 215,
        SpreadAlt = 0.0006,
        InaccuracyMove = 0.0697,
        InaccuracyLadder = 0.0913,
        Spread = 0.0006,
        InaccuracyStandAlt = 0.0054,
        RecoveryTimeStand = 0.4246,
        InaccuracyFireAlt = 0.0059,
        InaccuracyCrouch = 0.0041,
    },
    Bullets = 1,
    DefaultClip = 25,
    Range = 8192,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
CrosshairInfo = {
    x = 0,
    file = "sprites/crosshairs",
    y = 48,
    height = 24,
    width = 24,
},
WepSelData = {
    "CSweaponsSmall",
    "T",
},
IconOverride = "VGUI/gfx/VGUI/weapon_famas",
MaxInaccuracy = 1,
MuzzleFlashStyle = "CS_MUZZLEFLASH_X",
IdleInterval = 20,
TimeToIdle = 1.1,
})