-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_Aug",
WeaponType = "Rifle",
WorldModel = "models/weapons/w_rif_aug.mdl",
ViewModel = "models/weapons/v_rif_aug.mdl",
ViewModelFlip = true,
HoldType = "ar2",
Slot = 2,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = true,
MuzzleFlashScale = 1.3,
Sounds = {
    single_shot = "Weapon_AUG.Single",
},
Primary = {
    Ammo = "BULLET_PLAYER_762MM",
    Automatic = true,
    Damage = 32,
    Penetration = 2,
    ClipSize = 30,
    CycleTime = 0.09,
    Accuracy = {
        InaccuracyJumpAlt = 0.3693,
        RecoveryTimeCrouch = 0.3026,
        InaccuracyCrouchAlt = 0.0028,
        InaccuracyStand = 0.0054,
        InaccuracyJump = 0.3693,
        InaccuracyLandAlt = 0.0738,
        InaccuracyFire = 0.0109,
        InaccuracyLadderAlt = 0.0923,
        InaccuracyMoveAlt = 0.0726,
        InaccuracyLand = 0.0738,
        AccuracyOffset = 0.3,
        AccuracyDivisor = 215,
        SpreadAlt = 0.0006,
        InaccuracyMove = 0.0726,
        InaccuracyLadder = 0.0923,
        Spread = 0.0006,
        InaccuracyStandAlt = 0.0038,
        RecoveryTimeStand = 0.4236,
        InaccuracyFireAlt = 0.0109,
        InaccuracyCrouch = 0.0041,
    },
    Bullets = 1,
    DefaultClip = 30,
    Range = 8192,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
WepSelData = {
    "CSweaponsSmall",
    "E",
},
IconOverride = "VGUI/gfx/VGUI/weapon_aug",
MuzzleFlashStyle = "CS_MUZZLEFLASH_X",
IdleInterval = 20,
MaxInaccuracy = 1,
TimeToIdle = 1.9,
})