-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_Glock18",
WeaponType = "Pistol",
WorldModel = "models/weapons/w_pist_glock18.mdl",
ViewModel = "models/weapons/v_pist_glock18.mdl",
ViewModelFlip = true,
HoldType = "pistol",
Slot = 1,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = false,
MuzzleFlashScale = 1,
Sounds = {
    single_shot = "Weapon_Glock.Single",
},
Primary = {
    Ammo = "BULLET_PLAYER_9MM",
    Automatic = false,
    Bullets = 1,
    CycleTime = 0.15,
    ClipSize = 20,
    Penetration = 1,
    Accuracy = {
        InaccuracyJumpAlt = 0.2775,
        RecoveryTimeCrouch = 0.2187,
        InaccuracyCrouchAlt = 0.0075,
        InaccuracyStand = 0.01,
        InaccuracyJump = 0.2775,
        InaccuracyLandAlt = 0.0555,
        InaccuracyFire = 0.0316,
        InaccuracyLand = 0.0555,
        InaccuracyMove = 0.0166,
        InaccuracyMoveAlt = 0.0166,
        SpreadAlt = 0.004,
        InaccuracyLadderAlt = 0.0185,
        InaccuracyLadder = 0.0185,
        Spread = 0.004,
        InaccuracyStandAlt = 0.01,
        RecoveryTimeStand = 0.2624,
        InaccuracyFireAlt = 0.0221,
        InaccuracyCrouch = 0.0075,
    },
    Damage = 25,
    DefaultClip = 20,
    Range = 4096,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
CrosshairInfo = {
    x = 0,
    file = "sprites/crosshairs",
    y = 48,
    height = 24,
    width = 24,
},
WepSelData = {
    "CSweaponsSmall",
    "C",
},
IconOverride = "VGUI/gfx/VGUI/weapon_glock",
})