-- This file is subject to copyright - contact swampservers@gmail.com for more information.
-- INSTALL: CINEMA
-- This file was generated from the counter-strike source keyvalues file for this weapon. Please excuse the shitty formatting
AddCSLuaFile()
table.Merge(SWEP,{
Base = "weapon_css",
PrintName = "#Cstrike_WPNHUD_M4A1",
WeaponType = "Rifle",
WorldModel = "models/weapons/w_rif_m4a1.mdl",
ViewModel = "models/weapons/v_rif_m4a1.mdl",
ViewModelFlip = true,
HoldType = "ar2",
Slot = 2,
Spawnable = true,
Category = "Counter-Strike:Source",
CSMuzzleFlashes = true,
CSMuzzleX = true,
MuzzleFlashScale = 1.6,
Sounds = {
    special1 = "Weapon_M4A1.Silenced",
    single_shot = "Weapon_M4A1.Single",
    special2 = "Weapon_M4A1.Silencer_Off",
    special3 = "Weapon_M4A1.Silencer_On",
},
Primary = {
    Ammo = "BULLET_PLAYER_556MM",
    Automatic = true,
    Damage = 33,
    Penetration = 2,
    ClipSize = 30,
    CycleTime = 0.09,
    Accuracy = {
        InaccuracyJumpAlt = 0.3484,
        RecoveryTimeCrouch = 0.2697,
        InaccuracyCrouchAlt = 0.0052,
        InaccuracyStand = 0.007,
        InaccuracyJump = 0.3415,
        InaccuracyLandAlt = 0.0696,
        InaccuracyFire = 0.0126,
        AccuracyDivisor = 220,
        InaccuracyMoveAlt = 0.0703,
        InaccuracyLand = 0.0683,
        AccuracyOffset = 0.3,
        InaccuracyMove = 0.0687,
        SpreadAlt = 0.0005,
        InaccuracyLadderAlt = 0.0871,
        InaccuracyLadder = 0.0853,
        Spread = 0.0006,
        InaccuracyStandAlt = 0.007,
        RecoveryTimeStand = 0.3776,
        InaccuracyFireAlt = 0.0116,
        InaccuracyCrouch = 0.0052,
    },
    Bullets = 1,
    DefaultClip = 30,
    Range = 8192,
},
Secondary = {
    Ammo = "None",
    ClipSize = -1,
},
CrosshairInfo = {
    x = 0,
    file = "sprites/crosshairs",
    y = 48,
    height = 24,
    width = 24,
},
WepSelData = {
    "CSweaponsSmall",
    "W",
},
IconOverride = "VGUI/gfx/VGUI/weapon_m4a1",
IdleInterval = 60,
SilencerModel = "models/weapons/w_rif_m4a1_silencer.mdl",
MaxInaccuracy = 1,
TimeToIdle = 1.5,
})